### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by harlexkhal** [harlexkhal/Foodipy#21]
We are just 2 members on the team, you can find our Kanban board project [here](https://github.com/harlexkhal/JavaScript-Capstone/projects/1)

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by harlexkhal** [comment]
Thanks for the review 😉
