### ISSUE TITLE
[3pt]  - Add tests for items counter - Student A

### ISSUE THREAD

**Issue by harlexkhal** [harlexkhal/Foodipy#3]
Make sure that function for the items counter is covered with unit tests using Jest.

**Comment by mnekx** [comment]
The test follows the AAA pattern, one thing though: consider below:

![image](https://user-images.githubusercontent.com/22321030/157267331-778f6faa-4364-49aa-8c52-cfcceae6d2e8.png)
 The `describe` could be "Food Items" and `test` could be "count items" to better describe the test. Dont you think?
